import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { createMapReader, visiblePortals } from '../src/cloud/maps.js';
const require = createRequire(import.meta.url);
const { createDatabase } = require('../../app/test/helpers/shared-database.js');

test('web reader uses real app SQL permissions for personal maps, phone-only viewers and revoked membership', async t => {
  const server = await createDatabase();
  t.after(() => server.close());
  const alice = await server.rpc('alice', 'account_policy');
  const bob = await server.rpc('bob', 'account_policy');
  const room = await server.rpc('alice', 'create_map', { p_title: 'Phone viewers' });
  await server.rpc('alice', 'set_map_policy', { p_map: room, p_confirm: 0 });
  const edge = (a, b) => ({ a, b, source: 'manual', capMax: 7, capMaxKnown: true, expiresAt: new Date(Date.now() + 3600000).toISOString() });
  await server.rpc('alice', 'push_edges', { p_map: alice.personalMap, p_edges: [edge('Private A', 'Private B')] });
  await server.rpc('alice', 'push_edges', { p_map: room, p_edges: [edge('Group A', 'Group B')] });
  // A member can join using only the website RPC, without the desktop application.
  await server.rpc('bob', 'join_test_fixture', { p_map: room, p_title: null });
  const reader = createMapReader({ rpc: (name, body) => server.rpc('bob', name, body) });
  reader.setAccount(server.users.bob); await reader.refresh(); reader.select('all');
  let state = reader.getState();
  assert.equal(state.error, null);
  assert.deepEqual(state.maps.map(map => map.id), [bob.personalMap, room]);
  assert.equal(state.maps.find(map => map.id === room).role, 'viewer');
  assert.deepEqual(visiblePortals(state.maps, state.snapshots, 'all').map(edge => edge.a), ['Group A']);
  assert.equal((await server.rpc('bob', 'pull_map_snapshot', { p_map: alice.personalMap })).denied, true);
  assert.equal((await server.rpc('outsider', 'pull_map_snapshot', { p_map: room })).denied, true);
  await assert.rejects(server.rpc('bob', 'push_edges', { p_map: room, p_edges: [edge('Injected', 'Portal')] }));
  await server.rpc('alice', 'set_member_role', { p_map: room, p_user: server.users.bob, p_role: 'verified' });
  await reader.refresh();
  state = reader.getState();
  assert.equal(state.maps.find(map => map.id === room).role, 'verified');
  assert.equal(state.snapshots[room].role, 'verified');
  await reader.refresh();
  state = reader.getState();
  assert.equal(state.error, null, 'unchanged snapshots remain valid for verified members');
  assert.equal(visiblePortals(state.maps, state.snapshots, 'all').length, 1);
  await server.rpc('alice', 'set_map_policy', { p_map: room, p_confirm: 2 });
  await server.rpc('carol', 'join_test_fixture', { p_map: room, p_title: null });
  await server.rpc('alice', 'set_member_role', { p_map: room, p_user: server.users.carol, p_role: 'member' });
  await server.rpc('carol', 'push_edges', { p_map: room, p_edges: [edge('Unconfirmed A', 'Unconfirmed B')] });
  await reader.refresh();
  state = reader.getState();
  assert.deepEqual(visiblePortals(state.maps, state.snapshots, 'all').map(edge => edge.a), ['Group A'],
    'trusted owner report remains visible; unconfirmed member report is hidden from viewer');
  await server.db.exec('update public.billing_configuration set enabled = true, payment_ready = true');
  await reader.refresh();
  state = reader.getState();
  assert.equal(state.snapshots[room].status, 'paused');
  assert.equal(visiblePortals(state.maps, state.snapshots, 'all').length, 0, 'paused subscription exposes no cached group portals');
  await server.db.exec('update public.billing_configuration set enabled = false');
  await server.rpc('alice', 'kick_member', { p_map: room, p_user: server.users.bob });
  await reader.refresh();
  state = reader.getState();
  assert.equal(state.snapshots[room], undefined);
  assert.deepEqual(state.maps.map(map => map.id), [bob.personalMap]);
  await assert.rejects(server.rpc('unknown', 'pull_map_snapshot', { p_map: room }));
});
